import { StyleSheet } from 'react-native'

import { colors, radius, sp, type } from '@/theme/tokens'

export const styles = StyleSheet.create({
  flexBody: { flex: 1, minWidth: 0 },
  smallText: { ...type.small, color: colors.text, marginTop: sp(1) },
  successCard: { flexDirection: 'row', alignItems: 'flex-start', gap: sp(3) },
  steps: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: sp(4),
    paddingHorizontal: sp(1),
  },
  stepItem: { flex: 1, alignItems: 'center', position: 'relative' },
  stepIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  stepActive: { borderColor: colors.text, backgroundColor: colors.yellow },
  stepComplete: { borderColor: colors.text, backgroundColor: colors.primary },
  stepLabel: { fontSize: 10, color: colors.textMuted, marginTop: sp(1), fontWeight: '700' },
  stepLabelActive: { color: colors.text, fontWeight: '900' },
  stepLine: {
    height: 2,
    backgroundColor: colors.border,
    position: 'absolute',
    top: 16,
    left: '68%',
    width: '64%',
    zIndex: 1,
  },
  stepLineComplete: { backgroundColor: colors.primaryDark },
  cardHeadingRow: { flexDirection: 'row', alignItems: 'flex-start', gap: sp(3) },
  intro: { ...type.body, marginTop: sp(2), color: colors.text },
  privateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: sp(2),
    paddingVertical: sp(1),
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.primaryDark,
  },
  privateText: { fontSize: 11, color: colors.primaryDark, fontWeight: '800' },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: sp(2), marginTop: sp(4) },
  actionButton: {
    flexGrow: 1,
    flexBasis: 130,
    minHeight: 112,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
    padding: sp(3),
  },
  pressed: { opacity: 0.85, transform: [{ translateY: 2 }] },
  actionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sp(2),
  },
  actionLabel: { fontWeight: '900', color: colors.text },
  actionDetail: { ...type.small, marginTop: 2 },
  demoLink: {
    flexDirection: 'row',
    gap: sp(1),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sp(3),
    minHeight: 36,
  },
  demoLinkText: { color: colors.primaryDark, fontWeight: '800', fontSize: 13 },
  fileRules: { ...type.small, textAlign: 'center', marginTop: sp(1) },
  selectedFile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sp(3),
    marginTop: sp(4),
    padding: sp(3),
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  fileThumb: { width: 52, height: 52, borderRadius: radius.sm },
  fileIcon: {
    width: 52,
    height: 52,
    borderRadius: radius.sm,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fileName: { color: colors.text, fontWeight: '800' },
  fileMeta: { ...type.small, marginTop: 2 },
  parsingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sp(3),
    marginTop: sp(3),
    padding: sp(3),
    backgroundColor: colors.primarySoft,
    borderRadius: radius.md,
  },
  parsingTitle: { color: colors.text, fontWeight: '800' },
  parsingDetail: { ...type.small, marginTop: 2 },
  progressTrack: {
    height: 5,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    marginTop: sp(2),
    overflow: 'hidden',
  },
  progressFill: { width: '64%', height: '100%', backgroundColor: colors.primaryDark },
  messageBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sp(2),
    marginTop: sp(3),
    padding: sp(3),
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
  },
  message: { ...type.small, color: colors.text, flex: 1 },
  retryButton: {
    minHeight: 44,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.text,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sp(2),
    marginTop: sp(3),
  },
  reviewHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: sp(3) },
  hint: { ...type.small, marginTop: sp(1) },
  countBadge: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: sp(2),
    paddingVertical: sp(1.5),
    borderRadius: radius.pill,
  },
  countText: { color: colors.primaryDark, fontSize: 11, fontWeight: '900' },
  reportDetailsPanel: {
    marginTop: sp(4),
    padding: sp(3),
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
  },
  panelLabel: { ...type.label, color: colors.text },
  fieldRow: { flexDirection: 'row', flexWrap: 'wrap', gap: sp(2), marginTop: sp(2) },
  labeledInput: { flexGrow: 1, flexBasis: 150 },
  fieldLabel: { ...type.small, color: colors.textSecondary, marginBottom: sp(1) },
  input: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: sp(3),
    fontSize: 15,
  },
  futureNote: { fontSize: 11, color: colors.textMuted, lineHeight: 16, marginTop: sp(2) },
  reviewAlert: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sp(2),
    marginTop: sp(3),
    padding: sp(3),
    backgroundColor: '#FFF2D7',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#E9C680',
  },
  reviewAlertText: { ...type.small, color: colors.text, flex: 1, fontWeight: '600' },
  reviewToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: sp(4),
  },
  confirmAllText: { color: colors.primaryDark, fontWeight: '900', fontSize: 13 },
  candidate: {
    marginTop: sp(3),
    padding: sp(3),
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  candidateConfirmed: { borderColor: colors.primaryDark, backgroundColor: '#F4FAF1' },
  lowConfidence: { borderColor: colors.warning, backgroundColor: '#FFF9EC' },
  candidateHeader: { flexDirection: 'row', alignItems: 'center', gap: sp(2), marginBottom: sp(3) },
  confirmToggle: { flexDirection: 'row', alignItems: 'center', gap: sp(1) },
  confirmToggleText: { fontSize: 12, color: colors.text, fontWeight: '800' },
  attentionBadge: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
    backgroundColor: '#FFF2D7',
    paddingHorizontal: sp(2),
    paddingVertical: sp(1),
    borderRadius: radius.pill,
  },
  attentionText: { fontSize: 10, color: colors.warning, fontWeight: '900' },
  removeButton: { marginLeft: 'auto', padding: sp(1) },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: sp(1.5), marginTop: sp(3) },
  statusText: { ...type.small, fontWeight: '800' },
  confidence: { ...type.small, color: colors.textMuted, marginLeft: 'auto' },
  warning: { ...type.small, color: colors.warning, fontWeight: '700', marginTop: sp(2) },
  manualAdd: { flexDirection: 'row', alignItems: 'center', gap: sp(1), marginTop: sp(4) },
  manualAddText: { fontWeight: '800', color: colors.primaryDark },
  saveFooter: { marginTop: sp(4), paddingTop: sp(3), borderTopWidth: 1, borderTopColor: colors.border },
  saveSafety: { flexDirection: 'row', alignItems: 'center', gap: sp(2), marginBottom: sp(3) },
  saveSafetyText: { ...type.small, flex: 1 },
  saveButton: {
    backgroundColor: colors.text,
    borderRadius: radius.pill,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: sp(2),
    paddingHorizontal: sp(3),
  },
  disabled: { opacity: 0.5 },
  saveText: { color: colors.textOnColor, fontWeight: '900', textAlign: 'center' },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: sp(2),
    marginBottom: sp(3),
  },
  historySubtitle: { ...type.small, marginTop: 2 },
  historyIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.yellow,
    borderWidth: 1,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progress: { flexDirection: 'row', gap: sp(2), alignItems: 'center', marginTop: sp(3) },
  progressText: { fontWeight: '700', color: colors.text },
  emptyCard: { alignItems: 'center' },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sp(2),
  },
  empty: { ...type.small, textAlign: 'center', marginTop: sp(1) },
  errorText: { ...type.small, color: colors.danger, marginBottom: sp(2) },
  reportCard: { padding: sp(4) },
  reportHeader: { flexDirection: 'row', alignItems: 'center', gap: sp(3) },
  reportDocIcon: {
    width: 46,
    height: 46,
    borderRadius: radius.md,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportTitle: { fontSize: 16, fontWeight: '900', color: colors.text },
  reportMeta: { ...type.small, marginTop: 2 },
  expandButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: sp(2), marginTop: sp(3) },
  summaryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: sp(2),
    paddingVertical: sp(1),
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
  },
  flaggedBadge: { backgroundColor: '#FFF2D7' },
  summaryText: { fontSize: 11, fontWeight: '800', color: colors.text },
  reportDetail: { marginTop: sp(4), paddingTop: sp(3), borderTopWidth: 1, borderTopColor: colors.border },
  subsectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  verifiedLabel: { fontSize: 11, color: colors.primaryDark, fontWeight: '900' },
  metricRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sp(2),
    paddingVertical: sp(3),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  metricBody: { flex: 1, minWidth: 0 },
  metricName: { fontSize: 14, fontWeight: '800', color: colors.text },
  metricRange: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  metricValueBlock: { alignItems: 'flex-end', maxWidth: '48%' },
  metricValue: { fontSize: 14, fontWeight: '900', color: colors.text, textAlign: 'right' },
  metricStatus: { fontSize: 10, fontWeight: '800', marginTop: 2, textAlign: 'right' },
  adviceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: sp(5),
    marginBottom: sp(3),
  },
  adviceSubtitle: { ...type.small, marginTop: 2 },
  recBlock: { gap: sp(3) },
  rec: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sp(3),
    padding: sp(3),
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
  },
  recIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.yellow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recTitle: { fontSize: 15, fontWeight: '900', color: colors.text },
  recDetail: { ...type.small, color: colors.textSecondary, marginTop: sp(1), lineHeight: 19 },
  evidenceBox: { marginTop: sp(3) },
  evidenceLabel: { ...type.label, fontSize: 9 },
  evidenceList: { flexDirection: 'row', flexWrap: 'wrap', gap: sp(1), marginTop: sp(1) },
  evidenceChip: {
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    paddingHorizontal: sp(2),
    paddingVertical: sp(1),
    borderWidth: 1,
    borderColor: colors.border,
  },
  evidenceText: { fontSize: 10, color: colors.text, fontWeight: '700' },
  disclaimerCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sp(2),
    padding: sp(3),
    borderRadius: radius.md,
    backgroundColor: colors.primarySoft,
  },
  disclaimerTitle: { fontSize: 12, fontWeight: '900', color: colors.primaryDark },
  disclaimerText: { fontSize: 11, color: colors.textSecondary, lineHeight: 16, marginTop: 2 },
  adviceLocked: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sp(2),
    padding: sp(3),
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
  },
  adviceLockedText: { ...type.small, flex: 1 },
  recActions: { flexDirection: 'row', flexWrap: 'wrap', gap: sp(2), marginTop: sp(3) },
  recButton: {
    flexGrow: 1,
    flexBasis: 150,
    minHeight: 44,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.text,
    flexDirection: 'row',
    gap: sp(2),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: sp(3),
  },
  recButtonText: { fontWeight: '800', color: colors.text },
  recButtonDark: {
    flexGrow: 1,
    flexBasis: 130,
    minHeight: 44,
    borderRadius: radius.pill,
    backgroundColor: colors.text,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sp(1),
    paddingHorizontal: sp(3),
  },
  recButtonDarkText: { color: colors.textOnColor, fontWeight: '900' },
  deleteLink: { flexDirection: 'row', gap: sp(1), alignItems: 'center', marginTop: sp(4) },
  deleteText: { color: colors.danger, fontWeight: '800', fontSize: 13 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(31,33,29,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: sp(5),
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: colors.text,
    padding: sp(5),
  },
  modalIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FCE5DF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sp(3),
  },
  modalCopy: { ...type.body, marginTop: sp(2) },
  modalActions: { flexDirection: 'row', gap: sp(2), marginTop: sp(5) },
  modalCancel: {
    flex: 1,
    minHeight: 46,
    borderRadius: radius.pill,
    borderWidth: 1.5,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelText: { color: colors.text, fontWeight: '800' },
  modalDelete: {
    flex: 1,
    minHeight: 46,
    borderRadius: radius.pill,
    backgroundColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDeleteText: { color: colors.textOnColor, fontWeight: '900' },
})
