/**
 * Akeso domain types.
 *
 * Every App/API/AI shared shape lives in `@akeso/contracts` (Issue #6 —
 * FROZEN, with Zod runtime validation) and is re-exported here so existing
 * `@akeso/domain` imports keep working. Changing any re-exported shape
 * requires sign-off from all module owners (see docs/TEAM_CONTRACT.md §2).
 */

export type {
  ApiError,
  ApiResponse,
  CheckInInput,
  CoachReply,
  CoachSuggestion,
  CreateReportRequest,
  DayPlan,
  DietarySafetyProfile,
  DetectedIngredient,
  DietaryPreference,
  EnergyBand,
  EnergyAlgorithmVersion,
  EnergyCalibration,
  EnergyConfidence,
  EnergyCurvePoint,
  EnergyDemand,
  EnergyFactor,
  EnergyFactorKey,
  EnergyFactorRole,
  EnergyResult,
  EnergyHistorySample,
  DetectedReportMetric,
  FridgeCategory,
  FridgeItem,
  FoodAllergen,
  HealthReport,
  HealthRecommendation,
  HealthRecommendationBlueprint,
  HealthRecommendationBlueprintItem,
  HealthRecommendationCategory,
  HealthRecommendationProfileContext,
  HealthRecommendationSet,
  RecommendationActionCode,
  HourWindow,
  Hydration,
  IngredientRecognitionResult,
  LastMealTiming,
  ReportExtractionResult,
  ReportMetric,
  ReportMetricStatus,
  ReportName,
  MealRecommendation,
  MealSlot,
  NutrientKey,
  NutrientNeed,
  NutritionPlan,
  PlanBlock,
  PlanBlockType,
  ReminderPreference,
  PersonalBaseline,
  SaveEnergyCalibrationInput,
  Scale1to5,
  SleepDuration,
  Task,
  TaskPriority,
  TaskStatus,
  UpdatePlanBlockInput,
  UpdateReportMetricsRequest,
  UpdateReportRequest,
  UserGoal,
  UserProfile,
} from '@akeso/contracts'
